services:
  - type: web
    name: cv-website-backend
    env: node
    plan: free
    rootDir: cv-website-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5001
